# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uf850_api_pb2 as uf850__api__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uf850_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Uf850ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJointState = channel.unary_unary(
                '/uf850.Uf850Service/GetJointState',
                request_serializer=uf850__api__pb2.Empty.SerializeToString,
                response_deserializer=uf850__api__pb2.JointState.FromString,
                _registered_method=True)
        self.GetEEFPose = channel.unary_unary(
                '/uf850.Uf850Service/GetEEFPose',
                request_serializer=uf850__api__pb2.Empty.SerializeToString,
                response_deserializer=uf850__api__pb2.Pose.FromString,
                _registered_method=True)
        self.GetWrench = channel.unary_unary(
                '/uf850.Uf850Service/GetWrench',
                request_serializer=uf850__api__pb2.Empty.SerializeToString,
                response_deserializer=uf850__api__pb2.Wrench.FromString,
                _registered_method=True)
        self.SetJointTarget = channel.unary_unary(
                '/uf850.Uf850Service/SetJointTarget',
                request_serializer=uf850__api__pb2.JointState.SerializeToString,
                response_deserializer=uf850__api__pb2.StatusResponse.FromString,
                _registered_method=True)


class Uf850ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJointState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEEFPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWrench(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Uf850ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJointState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointState,
                    request_deserializer=uf850__api__pb2.Empty.FromString,
                    response_serializer=uf850__api__pb2.JointState.SerializeToString,
            ),
            'GetEEFPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEEFPose,
                    request_deserializer=uf850__api__pb2.Empty.FromString,
                    response_serializer=uf850__api__pb2.Pose.SerializeToString,
            ),
            'GetWrench': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWrench,
                    request_deserializer=uf850__api__pb2.Empty.FromString,
                    response_serializer=uf850__api__pb2.Wrench.SerializeToString,
            ),
            'SetJointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointTarget,
                    request_deserializer=uf850__api__pb2.JointState.FromString,
                    response_serializer=uf850__api__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uf850.Uf850Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uf850.Uf850Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Uf850Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJointState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uf850.Uf850Service/GetJointState',
            uf850__api__pb2.Empty.SerializeToString,
            uf850__api__pb2.JointState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEEFPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uf850.Uf850Service/GetEEFPose',
            uf850__api__pb2.Empty.SerializeToString,
            uf850__api__pb2.Pose.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWrench(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uf850.Uf850Service/GetWrench',
            uf850__api__pb2.Empty.SerializeToString,
            uf850__api__pb2.Wrench.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uf850.Uf850Service/SetJointTarget',
            uf850__api__pb2.JointState.SerializeToString,
            uf850__api__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
